export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000000000000000000000000000'

// in seconds
export const DB_WRITE_SLEEP = 1
export const API_FETCH_SLEEP = 1

export const TESTNET_ENDPOINT = 'https://sui-testnet.mystenlabs.com/graphql'
export const TABLE_DEPLOYED = 's3m-contracts-dev'

// key: (address_package, event_timestamp)
// rest: list of events (insert row)
export const CONTRACT_EVENTS_TABLE = 's3m-contracts-events-dev'

// key: (address, event_timestamp)
// rest: list of events
export const ADDRESS_EVENTS_TABLE = 's3m-address-events-dev'

// key: (address, ticker)
// rest: balance (upsert row)
export const BALANCES_TABLE = 's3m-balances-dev'

// key: (address, 'allocated' | 'unallocated')
// rest: amount, last_timestamp (upsert row)
export const ALLOCATION_TABLE = 's3m-allocation-dev'

// key: address_package,
// rest: last_timestamp of last event
export const LASTFETCH_TABLE = 's3m-contracts-lastfetch-dev'

// timestamp = timestamp in event
// ltimestamp = timestamp generated by server (UTC)
// address_package = address::package
// ticker = "$" + package.upper()
