name: Lint

description: Lint Code

inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: cd frontend && npm i && cd ../
      shell: bash

    - name: Super-linter
      uses: super-linter/super-linter@v6.3.0
      env:
        VALIDATE_ALL_CODEBASE: 'true'
        VALIDATE_JAVASCRIPT_ES: 'true'
        VALIDATE_TYPESCRIPT_ES: 'true'
        VALIDATE_JSX: 'true'
        VALIDATE_TSX: 'true'
        LINTER_RULES_PATH: .
        TYPESCRIPT_ES_CONFIG_FILE: frontend/.eslintrc.js
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
