name: Tests

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_call:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: cd frontend && npm i && cd ../

      - name: Run Tests
        run: cd frontend && npm test -- --reporters="jest-junit" && cd ../

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests Report     # Name of the check run which will be created
          path: frontend/junit.xml    # Path to test results
          reporter: jest-junit        # Format of test results
